[package]
name = "candle-scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# candle-nn = "0.3.1"
candle-nn = { path = "../others/candle/candle-nn", features = ["cuda"] }
